on: [push]
name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [22.2]
        elixir: [1.10.3]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: "root"
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@v1
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - uses: actions/cache@v1
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          
      - name: Install Dependencies
        run: mix deps.get

      - name: Linter
        run: mix format --check-formatted

      - name: Run Tests
        run: |
          source env/ci.env
          mix test

      - name: Code coverage
        run: |
          source env/ci.env
          mix test --cover